### ISSUE TITLE
HCLS footer change

### ISSUE THREAD

**Issue by ishanivardhan** [gncube/Alero#1]
Based on new contact details, footer info in HCLS website need to change such that we only show address with icon when address fields are not blank.
Also need to adjust the padding to fit email in footer in line with email icon

**Comment by gncube** [comment]
Hi @ishanivardhan, this has been done for you, Please check and confirm that it is working file.

**Comment by ishanivardhan** [comment]
@gncube - I haven't incorporated your last fix as I haven't been able to test that fix of yours. Would you be able to add an address to Web Support user on sandbox site for me to test please?
